---
- hosts: localhost
  become: True
  become_user: root
  vars:
    my_packages:
      - bind-utils
      - firefox
      - git
      - google-chrome-stable
      - httpd
      - kate
      - libreoffice
      - lightning
      - mariadb-server
      - phpMyAdmin
      - thunderbird
      - tmux
      - unzip
      - xsane
      - wget
      - zip
    my_users:
      - chantal
      - chantalthuis
    my_configfiles:
      - .bashrc
      - .git-prompt.sh

  tasks:
    - name: ensure packages
      dnf:
        name: "{{ my_packages }}"
        state: present
      tags: package

    - name: ensure users
      user:
        name:  "{{ item }}"
        group: "{{ item }}"
        groups: wheel
        append: true
        shell: /bin/bash
        state: present
      loop: "{{ my_users }}"
      tags: users

    - name: copy git prompt and bashrc
      copy:
        src: "{{ item[0] }}"
        dest: "/home/{{ item[1] }}/{{ item[0] }}"
        owner: "{{ item[1] }}"
        group: "{{ item[1] }}"
        mode: u=rw,g=r,o=r
      loop: "{{ q('nested',
        my_configfiles,
        my_users ) }}" 
      tags: userfiles

    # Creating a thunderbird profile directory, profiles.ini
    # and copying prefs.js should be enough to start up
    # thunderbird with the accounts I want.
    # Thunderbird creates the rest of the profile files
    # on the first startup.

    - name: create thunderbird directory 
      file:
        path: "/home/{{item}}/.thunderbird/{{item}}.default"
        state: directory
        recurse: true
        owner: "{{ item }}"
        group: "{{ item }}"
      loop: "{{ my_users }}"
      tags: thunderbird

    - name: copy thunderbird prefs
      template:
        src: "prefs.js.j2"
        dest: "/home/{{item}}/.thunderbird/{{item}}.default/prefs.js"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: u=rw,g=r,o=r
      loop: "{{ my_users }}"
      tags: thunderbird
    
    - name: copy thunderbird profile
      copy:
        src: profiles.ini
        dest: "/home/{{item}}/.thunderbird/profiles.ini"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: u=rw,g=r,o=r
      tags: thunderbird

