---
- hosts: localhost
  become: True
  become_user: root
  vars:
    my_packages:
      - bind-utils
      - firefox
      - git
      - google-chrome-stable
      - httpd
      - kate
      - libreoffice
      - lightning
      - mariadb-server
      - phpMyAdmin
      - thunderbird
      - tmux
      - unzip
      - xsane
      - wget
      - zip
    my_users:
      - chantal
      - chantalthuis
    my_configfiles:
      - .bashrc
      - .git-prompt.sh

  tasks:
    - name: ensure packages
      dnf:
        name: "{{ my_packages }}"
        state: present
      tags: package

    - name: ensure users
      user:
        name:  "{{ item }}"
        group: "{{ item }}"
        groups: wheel
        append: true
        shell: /bin/bash
        state: present
      loop: "{{ my_users }}"
      tags: users

    - name: copy git prompt and bashrc
      copy:
        src: "{{ item[0] }}"
        dest: "/home/{{ item[1] }}/{{ item[0] }}"
        owner: "{{ item[1] }}"
        group: "{{ item[1] }}"
        mode: u=rw,g=r,o=r
      loop: "{{ q('nested',
        my_configfiles,
        my_users ) }}" 
      tags: userfiles


